"""Export sentence maps as PDF or DOCX.

Generates a document with the indented clause-depth visualization
matching the full_blocks renderer output, using proper token coloring.
"""
from __future__ import annotations
import io
from typing import List, Tuple

from fpdf import FPDF
from docx import Document
from docx.shared import Pt, Inches, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH

from latin_reader.pipeline.renderer import (
    _map_token_depths,
    _build_token_type_map,
    CLAUSE_TYPES,
    _SUBORDINATE_TYPES,
    DEPTH_COLORS,
    CHUNK_TEXT_COLORS,
)
from latin_reader.pipeline.chunker import Chunk
from latin_reader.latincy_postprocessor.sentence import Token


# ─── Shared helpers ───────────────────────────────────────────────────────────

def _hex_to_rgb(hex_str: str) -> Tuple[int, int, int]:
    """Convert '#RRGGBB' to (R, G, B) ints."""
    h = hex_str.lstrip("#")
    return int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16)


def _build_segments(chunk: Chunk, tokens: List[Token]):
    """Build ordered segments of (depth, tids) for the sentence.

    Returns list of dicts with keys: depth, tids, clause.
    """
    token_map = {t.id: t for t in tokens}
    type_map: dict = {}
    _build_token_type_map(chunk, type_map)

    all_tids = sorted(chunk.flatten_token_ids())
    if not all_tids:
        return [], token_map, type_map

    tid_info: dict = {}
    _map_token_depths(chunk, 0, tid_info)
    for tid in all_tids:
        if tid not in tid_info:
            tid_info[tid] = (chunk, 0)

    segments = []
    for tid in all_tids:
        clause, depth = tid_info[tid]
        if (segments
                and segments[-1]["clause"] is clause
                and segments[-1]["depth"] == depth):
            segments[-1]["tids"].append(tid)
        else:
            segments.append({"clause": clause, "tids": [tid], "depth": depth})

    return segments, token_map, type_map


# ─── PDF Export ───────────────────────────────────────────────────────────────

INDENT_CHARS = 4  # spaces per indent level


def export_pdf(chunks_and_tokens: List[Tuple[Chunk, List[Token]]], title: str = "Latin Sentence Map") -> bytes:
    """Generate a PDF with indented clause visualization for each sentence."""
    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()

    # Title
    pdf.set_font("Helvetica", "B", 16)
    pdf.cell(0, 12, title, new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.ln(4)

    for sent_idx, (chunk, tokens) in enumerate(chunks_and_tokens):
        segments, token_map, type_map = _build_segments(chunk, tokens)
        if not segments:
            continue

        if sent_idx > 0:
            pdf.ln(4)

        for seg in segments:
            depth = max(0, seg["depth"])
            indent = " " * (depth * INDENT_CHARS)

            # Determine depth color for the line marker
            depth_idx = min(depth, len(DEPTH_COLORS) - 1)
            fill_hex, _ = DEPTH_COLORS[depth_idx]
            r, g, b = _hex_to_rgb(fill_hex)

            # Build the text for this line
            words = []
            for tid in seg["tids"]:
                tok = token_map.get(tid)
                if tok:
                    words.append(tok.form)
            line_text = indent + " ".join(words)

            # Draw a small colored depth indicator
            x = pdf.get_x()
            y = pdf.get_y()
            bar_x = 10 + depth * 8
            pdf.set_fill_color(r, g, b)
            pdf.rect(bar_x, y + 1, 3, 5, style="F")

            # Print the text
            pdf.set_font("Helvetica", "", 11)
            pdf.set_text_color(40, 40, 40)
            text_x = bar_x + 6
            pdf.set_x(text_x)

            # Use multi-part text with POS-based coloring
            for i, tid in enumerate(seg["tids"]):
                tok = token_map.get(tid)
                if not tok:
                    continue
                t_type = type_map.get(tid, "Token")
                color_hex = CHUNK_TEXT_COLORS.get(t_type, CHUNK_TEXT_COLORS.get("Token", "#333333"))
                cr, cg, cb = _hex_to_rgb(color_hex)
                # Darken colors for print (pastel colors are hard to read on white)
                cr = max(0, cr - 60)
                cg = max(0, cg - 60)
                cb = max(0, cb - 60)
                pdf.set_text_color(cr, cg, cb)
                prefix = " " if i > 0 and tok.upos != "PUNCT" and tok.form not in (",", ".", ";", ":", "?", "!") else ""
                pdf.write(6, prefix + tok.form)

            pdf.ln(7)

    pdf.set_text_color(120, 120, 120)
    pdf.set_font("Helvetica", "I", 8)
    pdf.ln(8)
    pdf.cell(0, 5, "Generated by Latin Sentence Mapper", align="C")

    return bytes(pdf.output())


# ─── DOCX Export ──────────────────────────────────────────────────────────────

def export_docx(chunks_and_tokens: List[Tuple[Chunk, List[Token]]], title: str = "Latin Sentence Map") -> bytes:
    """Generate a DOCX with indented clause visualization for each sentence."""
    doc = Document()

    # Title
    title_para = doc.add_heading(title, level=1)
    title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER

    for sent_idx, (chunk, tokens) in enumerate(chunks_and_tokens):
        segments, token_map, type_map = _build_segments(chunk, tokens)
        if not segments:
            continue

        if sent_idx > 0:
            doc.add_paragraph()  # spacer

        for seg in segments:
            depth = max(0, seg["depth"])
            para = doc.add_paragraph()
            para.paragraph_format.space_before = Pt(1)
            para.paragraph_format.space_after = Pt(1)
            para.paragraph_format.left_indent = Inches(depth * 0.3)

            # Depth color for a small marker
            depth_idx = min(depth, len(DEPTH_COLORS) - 1)
            fill_hex, _ = DEPTH_COLORS[depth_idx]
            dr, dg, db = _hex_to_rgb(fill_hex)

            # Add a colored depth marker
            marker = para.add_run("▌ ")
            marker.font.color.rgb = RGBColor(dr, dg, db)
            marker.font.size = Pt(10)

            # Add tokens with POS-based coloring
            for i, tid in enumerate(seg["tids"]):
                tok = token_map.get(tid)
                if not tok:
                    continue
                t_type = type_map.get(tid, "Token")
                color_hex = CHUNK_TEXT_COLORS.get(t_type, CHUNK_TEXT_COLORS.get("Token", "#333333"))
                cr, cg, cb = _hex_to_rgb(color_hex)
                # Darken for print readability
                cr = max(0, cr - 40)
                cg = max(0, cg - 40)
                cb = max(0, cb - 40)

                prefix = " " if i > 0 and tok.upos != "PUNCT" and tok.form not in (",", ".", ";", ":", "?", "!") else ""
                run = para.add_run(prefix + tok.form)
                run.font.size = Pt(11)
                run.font.color.rgb = RGBColor(cr, cg, cb)
                run.font.name = "Calibri"

    # Footer note
    footer = doc.add_paragraph()
    footer.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = footer.add_run("Generated by Latin Sentence Mapper")
    run.font.size = Pt(8)
    run.font.color.rgb = RGBColor(150, 150, 150)
    run.font.italic = True

    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()
